### ISSUE TITLE
Feature request: Add support for include presets

### ISSUE THREAD

**Issue by guillaume-michel** [darcamo/cmake-integration#10]
Hi, 
First thanks for your great work.

When using conan, I generate CMakeUserPresets.json file which actually include other CMakePresets.json file. This is an example of generated file:
```json
{
    "version": 4,
    "vendor": {
        "conan": {}
    },
    "include": [
        "/home/me/work/project/build/x86_64-gcc-11-use_cuda_true-release/generators/CMakePresets.json",
        "/home/me/work/project/build/x86_64-gcc-11-use_cuda_true-debug/generators/CMakePresets.json",
        "/home/me/work/project/build/x86_64-gcc-11-use_cuda_true-relwithdebinfo/generators/CMakePresets.json"
    ]
}
```
Unfortunately, cmake-integration does not support that. Is it possible for you to add it please?

Thanks

**Comment by darcamo** [comment]
This is now implemented. Please try it and report any problems.

**Comment by guillaume-michel** [comment]
This works like a charm! Thank you very much for your work!
