### ISSUE TITLE
Add hint to use `cmake-integration-cmake-reconfigure`

### ISSUE THREAD

**Issue by ktetzlaff** [darcamo/cmake-integration#2]
When I tried to use the cmake-integration commands, I was initially stumped that the promised target completion didn't work. I then figured out that I had to call `M-x cmake-integration-cmake-reconfigure` to create the required cmake API files.

You might want to explain that in README.md. Or, even better, check for the presence of the required API query/reply files when running cmake-integration commands which rely on it and inform users what to do if they are missing.

**Comment by darcamo** [comment]
Thanks for the feedback.

This is now written in the README file. Also, if the CMake query file is missing a warn will be shown asking the user to run one of the configure methods.

**Comment by ktetzlaff** [comment]
Thanks! 👍
