### ISSUE TITLE
Add support for clean and optional install targets

### ISSUE THREAD

**Issue by ktetzlaff** [darcamo/cmake-integration#5]
cmake-integration should offer to clean the build and, if configured, also allow to install targets. 

For the latter, the _codemodel_ can be used to determine if a target defines _install rules_ (unfortunately, in the _codemodel  configurations_ the relevant `hasInstallRule` attribute is part of the `directories` instead of `targets` vector which makes detection a bit cumbersome). If, for a given _configuration_, there is at least one directory with `hasInstallRule: true`, a corresponding top level `install/<config-name>` target should be added to the target list returned by `cmake-integration-get-cmake-targets-from-codemodel-json-file`.

Then, when the user requests building an _install target_, using compile command `cd <prjroot> && cmake --install <bindir> --config <config>` should do the trick.

**Comment by ktetzlaff** [comment]
Actually, using CMakes `--install` command really only installs existing targets. It doesn't build them. So a better alternative might be to `--build` the `--target install` which, at least for Ninja and Makefile generators, triggers _build_ followed by _install_.

**Comment by darcamo** [comment]
Adding a clean target is straightforward and there is no reason not to do it. It's the same with the "all" target that is already present.

On the other hand, if adding a install target is too cumbersome we might just not do it. It's not something you need often when developing and could be run from a terminal.

**Comment by darcamo** [comment]
I saw the pull request and it looks you got everything covered for the clean and install targets.
